version: 1
project_name: usque

builds:
  - id: usque-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: usque-linux-amd64
    builds:
      - usque-linux-amd64
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'sha256sums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'
